CREATE TABLE IF NOT EXISTS public.bounty_tag
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bounty_id uuid   NOT NULL,
    tag_id    bigint NOT NULL,
    CONSTRAINT bounty_tag_pkey PRIMARY KEY (id),
    CONSTRAINT bounty_tag_bounty_id_fkey FOREIGN KEY (bounty_id)
        REFERENCES public.bounties (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT bounty_tag_tag_id_fkey FOREIGN KEY (tag_id)
        REFERENCES public.tags (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);